version: 2.0
jobs:
  build_backend:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/mysql
    steps:
    - checkout
    - restore_cache:
       keys:
       - witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
       - witchcraft-app-
    - run:
        name: Build
        command: |
          DATABASE_NAME=circle_test \
          DATABASE_USERNAME=root \
          DATABASE_HOST=127.0.0.1 \
          ./gradlew witchcraft-app:build
    - save_cache:
        paths:
        - .gradle
        key: witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
    - store_test_results:
        path: WitchcraftApp/build/test-results
  deploy_backend_dev:
    working_directory: ~/witchcraft
      docker:
          - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: Setup CF cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.run.pivotal.io
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
     - run:
         name: Deploy to dev
         command: |
           cd WitchcraftApp
           cf push

  build_frontend:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
       keys:
       - witchcraft-node-modules-{{ checksum "package-lock.json" }}
       - witchcraft-node-modules-
    - run:
        name: Build
        command: ./gradlew frontend:build
    - save_cache:
        paths:
        - node_modules
        key: witchcraft-node-modules-{{ checksum "package-lock.json" }}
    - store_test_results:
        path: Frontend/build/test-results


workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - deploy_backend_dev:
          requires:
            - build_backend
      - build_frontend
