version: 2.1
jobs:
  build:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/mysql
    steps:
    - checkout
    - restore_cache: Restore .gradle
        keys:
        - witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
        - witchcraft-app-
    - restore_cache: Restore node_modules
        keys:
        - witchcraft-node-modules-{{ checksum "package-lock.json" }}
        - witchcraft-node-modules-

    - run: gradle build

    - save_cache: Save .gradle
        paths:
        - .gradle
        key: witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
    - save_cache: Save node_modules
        paths:
        - node_modules
        key: witchcraft-node-modules-{{ checksum "package-lock.json" }}