version: 2.0
jobs:
  build_backend:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/mysql
    steps:
    - checkout
    - restore_cache:
       keys:
       - witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
       - witchcraft-app-
    - run:
        name: Build
        command: |
          DATABASE_NAME=circle_test \
          DATABASE_USERNAME=root \
          DATABASE_HOST=127.0.0.1 \
          ./gradlew witchcraft-app:build
    - save_cache:
        paths:
        - .gradle
        key: witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
    - store_test_results:
        path: WitchcraftApp/build/test-results

  build_frontend:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - restore_cache:
       keys:
       - witchcraft-node-modules-{{ checksum "package-lock.json" }}
       - witchcraft-node-modules-
    - run:
        name: Build
        command: ./gradlew frontend:build
    - save_cache:
        paths:
        - node_modules
        key: witchcraft-node-modules-{{ checksum "package-lock.json" }}
    - store_test_results:
        path: Frontend/build/test-results


workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_frontend
