version: 2.1
jobs:
  build:
    working_directory: ~/witchcraft
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/mysql
    steps:
    - checkout
     - restore_cache:
         keys:
         - witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
         - witchcraft-app-
     - restore_cache:
         keys:
         - witchcraft-node-modules-{{ checksum "package-lock.json" }}
         - witchcraft-node-modules-

    - run:
        name: Build
        command: |
          DATABASE_NAME=circle_test \
          DATABASE_USERNAME=root \
          DATABASE_HOST=127.0.0.1 \
          ./gradlew build --info

     - save_cache:
         paths:
         - .gradle
         key: witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
     - save_cache:
         paths:
         - node_modules
         key: witchcraft-node-modules-{{ checksum "package-lock.json" }}
