version: 2.0
jobs:
  build_backend:
    working_directory: ~/witchcraft
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql
    steps:
      - checkout
      - restore_cache:
          keys:
            - witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
            - witchcraft-app-
      - run:
          name: Build
          command: |
            DATABASE_NAME=circle_test \
            DATABASE_USERNAME=root \
            DATABASE_HOST=127.0.0.1 \
            ./gradlew witchcraft-app:build
      - save_cache:
          key: witchcraft-app-{{ checksum "WitchcraftApp/build.gradle" }}
          paths:
            - .gradle
      - store_test_results:
          path: WitchcraftApp/build/test-results
      - persist_to_workspace:
          root: WitchcraftApp/build/libs
          paths:
            - witchcraft-app-0.0.1-SNAPSHOT.jar
  deploy_backend_dev:
    working_directory: ~/witchcraft
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: WitchcraftApp/build/libs
      - run:
          name: Setup CF cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.run.pivotal.io
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run:
          name: Deploy to dev
          command: |
            cd WitchcraftApp
            cf push

  build_frontend:
    working_directory: ~/witchcraft
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - witchcraft-node-modules-{{ checksum "Frontend/package-lock.json" }}
            - witchcraft-node-modules-
      - run:
          name: Build
          command: ./gradlew frontend:build -PbackendUrl=${BACKEND_DEV_URL}
      - save_cache:
          key: witchcraft-node-modules-{{ checksum "Frontend/package-lock.json" }}
          paths:
            - node_modules
      - store_test_results:
          path: Frontend/build/test-results
      - persist_to_workspace:
          root: Frontend/build/dist
  deploy_frontend_dev:
    working_directory: ~/witchcraft
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - attach_workspace:
          at: Frontend/build/dist
      - run:
          name: Setup CF cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api https://api.run.pivotal.io
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run:
          name: Deploy to dev
          command: |
            cd Frontend
            cf push


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_backend:
          filters:
            branches:
              only:
                - master
      - deploy_backend_dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build_backend
      - build_frontend:
          filters:
            branches:
              only:
                - master
      - deploy_frontend_dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build_frontend
