spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:witchcraft}?autoReconnect=true&useSSL=false
    username: ${DATABASE_USERNAME:spring}
    password:


management:
  endpoints:
    web:
      exposure.include: ${ACTUATOR_WEB_EXPOSURE:}
      cors.allowed-origins: ${FRONTEND_URL:http://localhost}
      cors.allowed-methods: GET
    jmx.exposure.exclude: "*"
  server.port: 8888
  endpoint.env.keys-to-sanitize: []




witchcraft.frontend.url: ${FRONTEND_URL:http://localhost:5000}