spring:
  jpa.hibernate.ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:witchcraft}?autoReconnect=true&useSSL=false
    username: ${DATABASE_USERNAME:spring}
    password:

witchcraft.frontend.url: ${FRONTEND_URL:http://localhost:5000}