spring:
  profiles: test
  jpa.hibernate:
    ddl-auto: create
  jpa.properties.hibernate:
    enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witchcraft_test?autoReconnect=true&useSSL=false
    username: spring
    password: