spring:
  profiles: test
  jpa.hibernate:
    ddl-auto: create
  jpa.properties.hibernate:
    enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_NAME:witchcraft_test}?autoReconnect=true&useSSL=false
    username: ${DATABASE_USERNAME:spring}
    password: