spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witchcraft?autoReconnect=true&useSSL=false
    username: spring
    password:
  thymeleaf:
    check-template-location: true
    suffix: .html
    prefix: classpath:/templates/
    cache: false

test-resources:
  recipe-url: SOME_RECIPE_HTTP_URL