spring:
  profiles: test
  jpa.hibernate:
    ddl-auto: create
  jpa.properties.hibernate:
    enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witchcraft_test?autoReconnect=true&useSSL=false
    username: spring
    password:

test-resources:
  recipe:
    url: https://www.cookincanuck.com/mini-goat-cheese-stuffed-potato-appetizers/
    name: "Mini Goat Cheese Stuffed Potato Appetizers – Greek-Inspired"
    img-url: https://www.cookincanuck.com/wp-content/uploads/2017/11/Mini-Goat-Cheese-Stuffed-Potato-Appetizers-Greek-Inspired-Cookin-Canuck-4.jpg
    ingredients[0]:
      name: Little Potato Co. Creamer potatoes (I used Dynamic Duo)
      quantity: 1.5
      unit: lb
    ingredients[1]:
      name: soft goat cheese (chevre), room temperature
      quantity: 4
      unit: oz
    ingredients[2]:
      name: diced roasted red pepper
      quantity: 3
      unit: tbsp
    ingredients[3]:
      name: pitted Kalamata olives, diced
      quantity: 4
      unit:
    ingredients[4]:
      name: minced flat-leaf parsley
      quantity: 1
      unit: tbsp
    ingredients[5]:
      name: pistachios halves, divided
      quantity: 3
      unit: tbsp
    ingredients[6]:
      name: honey
      quantity: 1
      unit: tsp
    ingredients[7]:
      name: ground cinnamon
      quantity: 0.25
      unit: tsp
    steps[0]:
      name: Place the potatoes in a large saucepan and cover with cold water by an inch. Bring to a boil. Cook until the potatoes are tender when pierced with a fork, but not falling apart, 15 to 20 minutes. Drain and let the potatoes rest until cool enough to handle.
    steps[1]:
      name: While the potatoes are cooking, prepare the fillings. In the first bowl, stir together the goat cheese roasted red pepper and Kalamata olives.
    steps[2]:
      name: In the second bowl, stir together the goat cheese, 2 tablespoons pistachios and honey.
    steps[3]:
      name: Using a small, sharp knife, cut a small slice off of the bottom of each potato so that they sit flat. Cut a small circle out of the top of each potato, then scoop out some of the flesh with a ¼ teaspoon measuring spoon. Reserve the flesh and top for another use (mix into mashed potatoes!)
    steps[4]:
      name: Scoop about 1 teaspoon of the savory filling into half of the potatoes (you could choose one color of potato) and garnish with parsley. Scoop the sweet filling into the remaining half of the potatoes and garnish with the remaining pistachios.
    steps[5]:
      name: Arrange on a serving plate. Serve.