spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/witchcraft?autoReconnect=true&useSSL=false
    username: spring
    password:
  data.rest:
    basePath: /api
    detection-strategy: annotated

logging.level.org.springframework.web: DEBUG

test-resources:
  recipe-url: SOME_RECIPE_HTTP_URL